import csv
import oracledb
from Database.DBConnect import get_connection
import os


def setup():
    """
    Creates database structure, it's tables for rental.
    Then imports data into those tables.
    :return: Connection or None when exception occurs.
    """
    connection = get_connection()

    cursor = connection.cursor()
    tables_to_drop = ["Rental_Items", "Rentals", "Machines", "Customers", "Categories"]

    for table in tables_to_drop:
        try:
            cursor.execute(f"drop table {table} cascade constraints")
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            print(error_obj)
    commands = [
        """create table Categories (
            id number generated by default as identity primary key, 
            name varchar2(100) not null, 
            power varchar2(50) not null check(power in ('diesel', 'electric', 'hybrid'))
        )""",
        """create table Customers (
            id number generated by default as identity primary key, 
            company_name varchar2(100), 
            name varchar2(50), 
            surname varchar2(50), 
            email varchar2(100) unique not null, 
            registration_date date default sysdate
        )""",
        """create table Machines (
            id number generated by default as identity primary key, 
            model varchar2(100), 
            weight number(10,2), 
            is_available number default 1 check(is_available in (0, 1)), 
            id_category number not null, 
            foreign key(id_category) references Categories(id)
        )""",
        """create table Rentals (
            id number generated by default as identity primary key, 
            customer_id number not null, 
            created timestamp default current_timestamp, 
            note varchar2(500),
            foreign key (customer_id) references Customers(id)
        )""",
        """create table Rental_Items (
            rental_id number not null, 
            machine_id number not null, 
            price_per_day number(10,2) not null, 
            days_count number,
            foreign key (rental_id) references Rentals(id), 
            foreign key (machine_id) references Machines(id),
            primary key (rental_id, machine_id)
        )"""
    ]

    try:
        for cmd in commands:
            cursor.execute(cmd)
        connection.commit()
        print("Tables created.")
        import_data(cursor, "categories.csv", "insert into Categories(name, power) values(:1, :2)")
        import_data(cursor, "customers.csv",
                    "insert into Customers(company_name, name, surname, email) values(:1, :2, :3, :4)")
        import_data(cursor, "machines.csv",
                    "insert into Machines(model, weight, is_available, id_category) values(:1, :2, :3, :4)")
        import_data(cursor, "rentals.csv",
                    "insert into Rentals(customer_id, note) values(:1, :2)")
        import_data(cursor, "rental_items.csv",
                    "insert into Rental_Items(rental_id, machine_id, price_per_day, days_count) values(:1, :2, :3, :4)")
        connection.commit()
        views = [
            """create or replace view Available_machines as 
               select m.id, m.model, m.weight, c.name as category_name, c.power 
               from Machines m 
               join Categories c on m.id_category = c.id 
               where m.is_available = 1""",
            """create or replace view Customer_revenue as 
               select cust.company_name, count(r.id) as total_rentals, 
               sum(ri.price_per_day * ri.days_count) as total_spent 
               from Customers cust 
               left join Rentals r on cust.id = r.customer_id 
               left join Rental_Items ri on r.id = ri.rental_id
               group by cust.company_name""",
            """create or replace view Machine_usage as 
               select m.model, cat.name as category, 
               count(ri.rental_id) as times_rented, 
               sum(ri.days_count) as total_days_in_field,
               max(ri.price_per_day) as highest_daily_rate,
               sum(ri.price_per_day * ri.days_count) as total_revenue_generated 
               from Machines m
               join Categories cat on m.id_category = cat.id 
               left join Rental_Items ri on m.id = ri.machine_id 
               group by m.model, cat.name"""
        ]
        for view in views:
            cursor.execute(view)
        connection.commit()
        print("Views created")
    except Exception as e:
        print(f"Tables couldn't be created. -  {e}")
        connection.rollback()
    finally:
        cursor.close()
        connection.close()


def import_data(cursor, file, query):
    """
    Reads csv files and prepares it to insert into database tables.
    :param cursor: connection.cursor
    :param file: file that is being read
    :param query: insertion that will happen
    :return: list of rows
    """
    cur_dir = os.path.dirname(__file__)
    data_path = os.path.abspath(os.path.join(cur_dir, "../..", "Data"))
    full_path = os.path.join(data_path, file)
    try:
        with open(full_path, "r", encoding="utf-8") as fil:
            reader = csv.reader(fil)
            next(reader)
            data = []
            for row in reader:
                if file == "machines.csv":
                    clear_float = (row[0], float(row[1]), int(row[2]), int(row[3]))
                    data.append(clear_float)
                elif file == "rental_items.csv":
                    clear_data = (int(row[0]), int(row[1]), float(row[2]), int(row[3]))
                    data.append(clear_data)
                elif file == "rentals.csv":
                    clear_data = (int(row[0]), row[1])
                    data.append(clear_data)
                else:
                    data.append(row)
            cursor.executemany(query, data)
            print("Success data imported")
    except FileNotFoundError:
        print("File not found.")
    except Exception as e:
        print(f"Something went wrong with importing data: {e}")


if __name__ == "__main__":
    setup()
